export interface Airport {
  value: string;
  label: string;
}

export const airports: Airport[] = [
  // Brasil
  { value: "BHZ", label: "Belo Horizonte - Todos os aeroportos" },
  { value: "PLU", label: "Belo Horizonte - Pampulha (PLU)" },
  { value: "AFL", label: "Alta Floresta (AFL)" },
  { value: "AJU", label: "Aracaju (AJU)" },
  { value: "BEL", label: "Belém (BEL)" },
  { value: "BVB", label: "Boa Vista (BVB)" },
  { value: "BSB", label: "Brasília (BSB)" },
  { value: "CGR", label: "Campo Grande (CGR)" },
  { value: "CWB", label: "Curitiba (CWB)" },
  { value: "FOR", label: "Fortaleza (FOR)" },
  { value: "FLN", label: "Florianópolis (FLN)" },
  { value: "GYN", label: "Goiânia (GYN)" },
  { value: "IGU", label: "Foz do Iguaçu - Iguazu Falls (IGU)" },
  { value: "JPA", label: "João Pessoa (JPA)" },
  { value: "LDB", label: "Londrina (LDB)" },
  { value: "MCZ", label: "Maceió (MCZ)" },
  { value: "MAO", label: "Manaus (MAO)" },
  { value: "NAT", label: "Natal (NAT)" },
  { value: "POA", label: "Porto Alegre (POA)" },
  { value: "PVH", label: "Porto Velho (PVH)" },
  { value: "REC", label: "Recife (REC)" },
  { value: "RBR", label: "Rio Branco (RBR)" },
  { value: "RIO", label: "Rio de Janeiro - Todos os aeroportos" },
  { value: "GIG", label: "Rio de Janeiro - Galeão (GIG)" },
  { value: "SDU", label: "Rio de Janeiro - Santos Dumont (SDU)" },
  { value: "SAO", label: "São Paulo - Todos os aeroportos" },
  { value: "GRU", label: "São Paulo - Guarulhos (GRU)" },
  { value: "CGH", label: "São Paulo - Congonhas (CGH)" },
  { value: "VCP", label: "São Paulo - Viracopos (VCP)" },
  { value: "SLZ", label: "São Luís (SLZ)" },
  { value: "SSA", label: "Salvador (SSA)" },
  { value: "THE", label: "Teresina (THE)" },
  { value: "UDI", label: "Uberlândia (UDI)" },
  { value: "VIX", label: "Vitória (VIX)" },
  { value: "VDC", label: "Vitória da Conquista (VDC)" },

  // Internacional
  { value: "MIA", label: "Miami, Estados Unidos (MIA)" },
  { value: "JFK", label: "Nova York - JFK, Estados Unidos (JFK)" },
  { value: "EWR", label: "Nova York - Newark, Estados Unidos (EWR)" },
  { value: "MCO", label: "Orlando, Estados Unidos (MCO)" },
  { value: "LAX", label: "Los Angeles, Estados Unidos (LAX)" },
  { value: "LIS", label: "Lisboa, Portugal (LIS)" },
  { value: "MAD", label: "Madri, Espanha (MAD)" },
  { value: "BCN", label: "Barcelona, Espanha (BCN)" },
  { value: "CDG", label: "Paris, França (CDG)" },
  { value: "FCO", label: "Roma, Itália (FCO)" },
  { value: "LHR", label: "Londres, Reino Unido (LHR)" },
  { value: "MEX", label: "Cidade do México, México (MEX)" },
  { value: "SCL", label: "Santiago, Chile (SCL)" },
  { value: "EZE", label: "Buenos Aires - Ezeiza, Argentina (EZE)" },
  { value: "AEP", label: "Buenos Aires - Aeroparque, Argentina (AEP)" },
  { value: "MVD", label: "Montevidéu, Uruguai (MVD)" },
  { value: "LIM", label: "Lima, Peru (LIM)" },
  { value: "BOG", label: "Bogotá, Colômbia (BOG)" },
  { value: "PTY", label: "Cidade do Panamá, Panamá (PTY)" },
  { value: "CUN", label: "Cancún, México (CUN)" },
];
